[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.2.6"

[[constraint]]
  branch = "master"
  name = "github.com/olebedev/config"

[[constraint]]
  name = "github.com/gosimple/slug"
  version = "1.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/ungerik/go-dry"
